"""Type stubs for oauth module."""

from typing import Optional, List
from google.oauth2.credentials import Credentials

def get_scopes() -> List[str]: ...
def login() -> str: ...
def process_auth_code(code: str, state: str) -> str: ...
def start_oauth_process(timeout: int = 300) -> bool: ...
def get_credentials() -> Optional[Credentials]: ...
