"""Type stubs for mcp tools package."""

from mcp.server.fastmcp import FastMCP

def setup_tools(mcp: FastMCP) -> None: ...
def setup_auth_tools(mcp: FastMCP) -> None: ...
def setup_email_read_tools(mcp: FastMCP) -> None: ...
def setup_email_send_tools(mcp: FastMCP) -> None: ...
def setup_email_manage_tools(mcp: FastMCP) -> None: ...
def setup_label_tools(mcp: FastMCP) -> None: ...
def setup_attachment_tools(mcp: FastMCP) -> None: ...
def setup_bulk_tools(mcp: FastMCP) -> None: ...
def setup_calendar_tools(mcp: FastMCP) -> None: ...
def setup_filter_tools(mcp: FastMCP) -> None: ...
def setup_vault_tools(mcp: FastMCP) -> None: ...
def setup_conflict_tools(mcp: FastMCP) -> None: ...
